collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.8168636
color:
  saturation: 0
  brandStrength: 0.8029001
  lightness: 1
  brandColors:
    - '#9EFBFF'
    - '#01190C'
    - '#021EFF'
    - '#ABA3FF'
    - '#42FBFF'
  rhythmicContrast: 0.4452202
layout_spectrum: 1
name: Hunting w/ Wictor
