collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8168636
color:
  saturation: 0.5182596
  brandStrength: 0.8029001
  lightness: 0.6578782
  brandColors:
    - '#9EFBFF'
    - '#01190C'
    - '#021EFF'
    - '#ABA3FF'
    - '#42FBFF'
  rhythmicContrast: 0.8113012
layout_spectrum: 1
name: Hunting w/ Wictor
